/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollapseSideBar: typeof import('../components/x-collapse/XCollapse.vue')['default']
    HomeDashBoard: typeof import('../views/home/HomeDashBoard.vue')['default']
    HomeSideBar: typeof import('../views/home/HomeSideBar.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    XCollapse: typeof import('./../components/x-collapse/XCollapse.vue')['default']
    XCollapseItem: typeof import('./../components/x-collapse/XCollapseItem.vue')['default']
  }
}
